1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
a = np.empty((2,2))
a

array([[1.42740183e-315, 0.00000000e+000],
       [2.89468780e-229, 1.81320626e-287]])

2.Initialize an all one array with size 4X2.

In [ ]:
import numpy as np
b = np.ones((4,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np
c = np.full((3,3), 9)
c

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

4.Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
arr = np.zeros_like(a)
arr

array([[0, 0, 0],
       [0, 0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [ ]:
import numpy as np
a = np.array([[2,3,4],[5,7,8]])
newa = np.ones_like(a)
newa

array([[1, 1, 1],
       [1, 1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
new_list = [1,2,3,4]
arr = np.array(new_list)
arr

array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np
K = np.arange(10,50)
K

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np
array = np.random.random(30)
mean_c = array.mean()
mean_c

np.float64(0.595555647947518)

5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
Z = np.random.random((10,10))
Zmin = Z.min()
Zmax = Z.max()
print("Z min:",Zmin)
print("Z max:",Zmax)


Z min: 0.015100285227000576
Z max: 0.9987744059417819


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np
y = np.zeros(10)
y[4] = 2
print(y)

[0. 0. 0. 0. 2. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
reverse_arr = arr[::-1]
print(reverse_arr)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np
arr = np.ones((6, 6))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
print("Checkboard Pattern: ")
x = np.zeros((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

Checkboard Pattern: 
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:

1. Add the two array.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
sum_xy = x + y
print("Sum of two array: ",sum_xy)

v = np.array([9,10])
w = np.array([11,12])
sum_vw = v + w
print("Sum of two array: ",sum_vw)

Sum of two array:  [[ 6  8]
 [10 13]]
Sum of two array:  [20 22]


2. Subtract the two array.

In [ ]:
import numpy as np
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6],
              [7,8]])
sub_xy = x - y
print("Subtractton of two array: ",sub_xy)

v = np.array([9,10])
w = np.array([11,12])
sub_vw = v - w
print("Subtracttion of two array: ",sub_vw)

Subtract of two array:  [[-4 -4]
 [-4 -3]]
Subtract of two array:  [-2 -2]


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6],
              [7,8]])
mul_xy = x * y
print("Multiplication of two array: ",mul_xy)

v = np.array([9,10])
w = np.array([11,12])
mul_vw = v * w
print("Multiplication of two array: ",mul_vw)

Multiplication of two array:  [[ 5 12]
 [21 40]]
Multiplication of two array:  [ 99 120]


4. Find the square of each element of the array.

In [ ]:
import numpy as np
x = np.array([[1,2],
              [3,5]])
x_square = x ** 2
print("Square of x: ",x_square)

y = np.array([[5,6],
              [7,8]])
y_square = y ** 2
print("Square of y: ",y_square)

v = np.array([9,10])
v_square = v ** 2
print("Square of v: ",v_square)

w = np.array([11,12])
w_square = w ** 2
print("Square of w: ",w_square)


Square of x:  [[ 1  4]
 [ 9 25]]
Square of y:  [[25 36]
 [49 64]]
Square of v:  [ 81 100]
Square of w:  [121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6],
              [7,8]])
v = np.array([9,10])
w = np.array([11,12])

dot_vw = np.dot(v, w)
print("v . w: ",dot_vw)

dot_xv = np.dot(x, v)
print("x . v: ", dot_xv)

dot_xy = np.dot(x, y)
print("x . y: \n", dot_xy)



v . w:  219
x . v:  [29 77]
x . y: 
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.





In [ ]:
import numpy as np
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6],
              [7,8]])
v = np.array([9,10])
w = np.array([11,12])

concate_xy_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along row: \n", concate_xy_row)

concate_vw_col = np.vstack((v, w)).T
print("Concatenate v and w with vstack: \n",concate_vw_col)

Concatenate x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w with vstack: 
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
x = np.array([[1,2],
              [3,5]])
v = np.array([9,10])

concate_xv = np.concatenate((x, v), axis=0)
print(concate_xv)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

I got the error because x array has 2d array whereas v has 1D array. And np.concatenate requires to have same number of dimensions along the axis.


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:

1. Prove A.A−1 = I.

In [ ]:
import numpy as np
A = np.array([[3,4],
              [7,8]])
B = np.array([[5,3],
            [2,1]])

A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A^-1: \n",I)

A * A^-1: 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.


In [ ]:
import numpy as np
A = np.array([[3,4],
              [7,8]])
B = np.array([[5,3],
            [2,1]])

AB = np.dot(A, B)
print("AB:\n ",AB)
BA = np.dot(B, A)
print("BA:\n ",BA)

print("AB == BA?: \n", np.array_equal(AB, BA))


AB:
  [[23 13]
 [51 29]]
BA:
  [[36 44]
 [13 16]]
AB == BA?: 
 False


3. Prove (AB)^T = B^TA^T

In [ ]:
import numpy as np
A = np.array([[3,4],
              [7,8]])
B = np.array([[5,3],
            [2,1]])

AB = np.dot(A, B)
AB_T = AB.T
print("(AB)^T: \n",AB_T)

BT_AT = np.dot(B.T, A.T)
print("B^T . A^T: \n", BT_AT)

print("(AB)^T == B^T . A^T?: \n", np.array_equal(AB_T, BT_AT))

(AB)^T: 
 [[23 51]
 [13 29]]
B^T . A^T: 
 [[23 51]
 [13 29]]
(AB)^T == B^T . A^T?: 
 True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])
K = np.linalg.solve(A, B)
print("Solution of [x,y,z]: \n",K)

Solution of [x,y,z]: 
 [ 2.  1. -2.]


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv =  np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution of [x, y, z]: \n",X)

Solution of [x, y, z]: 
 [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [ ]:
import numpy as np
import time

size = 1000000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
sum_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("python list additon time:", end - start, "seconds")

python list additon time: 0.12341570854187012 seconds


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time
size = 1000000

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
sum_array = arr1 + arr2
end = time.time()
print("NumPy array addition time:", end - start ,"seconds")

NumPy array addition time: 0.0020275115966796875 seconds


Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

In [ ]:
import numpy as np
import time
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()
mul_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("python list multiplication time:", end - start, "seconds")


python list multiplication time: 0.12583541870117188 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time
size = 1000000

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
mul_array = arr1 * arr2
end = time.time()
print("NumPy array multiplication time:", end - start ,"seconds")

NumPy array multiplication time: 0.003271341323852539 seconds


Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [ ]:
import numpy as np
import time
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()
dot_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("python list dot product time:", end - start, "seconds")


python list dot product time: 0.11738061904907227 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time
size = 1000000

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
dot_array = np.dot(arr1, arr2)
end = time.time()
print("NumPy array dot product time:", end - start ,"seconds")

NumPy array dot product time: 0.002416849136352539 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

In [5]:
import numpy as np
import time
size = 1000

mat1 = [[i + j for j in range(size)] for i in range(size)]
mat2 = [[i + j for j in range(size)] for i in range(size)]

start = time.time()

result = [[0]* size for _ in range(size)]

for i in range(size):
  for j in range(size):
    for k in range(size):
      result[i][j] += mat1[i][k] * mat2[k][j]

end = time.time()
print("python list matrix multiplication time: ", end - start , "seconds")

python list matrix multiplication time:  0.24749994277954102 seconds


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [1]:
import numpy as np
import time
size = 1000

mat1_np = np.arange(size*size).reshape(size, size)
mat2_np = np.arange(size*size).reshape(size, size)

start = time.time()
result_np = np.dot(mat1_np, mat2_np)
end = time.time()

print("NumPy matrix multiplication time:", end - start, "seconds")

NumPy matrix multiplication time: 2.6822078227996826 seconds
